const crosswordWords3 = {
    length: 3,
    words: [
      ["ACE", "Expert performer"],
      ["ACT", "Performance role"],
      ["AGE", "Length of existence"],
      ["AIR", "Invisible gas mixture"],
      ["ANT", "Small social insect"],
      ["APE", "Large tailless primate"],
      ["ASH", "Gray powdery residue"],
      ["AXE", "Wood-cutting tool"],
      ["BAD", "Poor quality"],
      ["BAR", "Drinking establishment"],
      ["BAT", "Nocturnal flying mammal"],
      ["BAY", "Coastal inlet"],
      ["BEE", "Honey-producing insect"],
      ["BET", "Wagered risk"],
      ["BIB", "Neck-worn protector"],
      ["BIG", "Large size"],
      ["BIN", "Storage container"],
      ["BIT", "Small piece"],
      ["BOA", "Long feathered scarf"],
      ["BOG", "Wet spongy ground"],
      ["BOX", "Rectangular container"],
      ["BOY", "Male child"],
      ["BUN", "Small bread roll"],
      ["BUS", "Public transport vehicle"],
      ["BUT", "Contrasting word"],
      ["CAB", "Hired vehicle"],
      ["CAN", "Metal container"],
      ["CAP", "Head covering"],
      ["CAR", "Four-wheeled vehicle"],
      ["CAT", "Small pet feline"],
      ["CUP", "Drinking vessel"],
      ["CUT", "Act of slicing"],
      ["DAY", "Twenty-four hours"],
      ["DEN", "Small private room"],
      ["DEW", "Morning moisture"],
      ["DIG", "Break ground"],
      ["DOG", "Domestic canine"],
      ["DOT", "Small round mark"],
      ["DRY", "Without moisture"],
      ["DUE", "Owed payment"],
      ["DYE", "Coloring substance"],
      ["EAR", "Hearing organ"],
      ["EEL", "Slender fish"],
      ["EGG", "Oval reproductive object"],
      ["END", "Final point"],
      ["ERA", "Notable time period"],
      ["EVE", "Day before event"],
      ["EYE", "Vision organ"],
      ["FAN", "Device for airflow"],
      ["FAR", "Great distance"],
      ["FAT", "Stored body tissue"],
      ["FAX", "Telecopied message"],
      ["FEW", "Small number"],
      ["FIG", "Sweet fruit"],
      ["FIN", "Fish appendage"],
      ["FIT", "Proper size"],
      ["FIX", "Repair action"],
      ["FLY", "Winged insect"],
      ["FOG", "Low thick cloud"],
      ["FOR", "In favor of"],
      ["FOX", "Wild canine animal"],
      ["FUN", "Enjoyable activity"],
      ["FUR", "Animal hair"],
      ["GAS", "Vapor fuel"],
      ["GEM", "Precious stone"],
      ["GET", "Obtain something"],
      ["GIN", "Clear alcoholic spirit"],
      ["GOD", "Supreme deity"],
      ["GUM", "Chewing confection"],
      ["GUN", "Projectile weapon"],
      ["GUT", "Stomach area"],
      ["GUY", "Male person"],
      ["HAM", "Cured pork meat"],
      ["HAT", "Headwear item"],
      ["HEM", "Edge of fabric"],
      ["HEN", "Female chicken"],
      ["HER", "Belonging to a woman"],
      ["HEY", "Attention call"],
      ["HIM", "Referring to a man"],
      ["HIP", "Upper leg joint"],
      ["HOG", "Large farm pig"],
      ["HOT", "High temperature"],
      ["HUE", "Color shade"],
      ["ICE", "Frozen water"],
      ["INK", "Writing fluid"],
      ["JAM", "Fruit preserve"],
      ["JAR", "Glass container"],
      ["JET", "High-speed aircraft"],
      ["JOB", "Work position"],
      ["JOY", "Great happiness"],
      ["KEY", "Unlocking instrument"],
      ["KID", "Young child"],
      ["KIN", "Family relatives"],
      ["LAB", "Scientific workspace"],
      ["LAP", "Upper leg topside"],
      ["LAW", "Legal system"],
      ["LAY", "Place down"],
      ["LEG", "Lower limb"],
      ["LET", "Allow permission"],
      ["LID", "Covering top"],
      ["LOG", "Cut tree segment"],
      ["LOT", "Large amount"],
      ["MAN", "Adult male"],
      ["MAP", "Geographic diagram"],
      ["MAT", "Floor covering"],
      ["MET", "Came together"],
      ["MIX", "Combine ingredients"],
      ["MUG", "Coffee cup"],
      ["NAP", "Short sleep"],
      ["NET", "Mesh fabric"],
      ["NOD", "Head gesture"],
      ["OAK", "Large hardwood tree"],
      ["OAR", "Rowing paddle"],
      ["OIL", "Viscous liquid"],
      ["OLD", "Long-lived"],
      ["ONE", "Single unit"],
      ["OUT", "Not inside"],
      ["OWL", "Nocturnal bird"],
      ["PAD", "Soft cushion"],
      ["PAL", "Close friend"],
      ["PAN", "Cooking vessel"],
      ["PEN", "Writing tool"],
      ["PEW", "Church bench"],
      ["PIG", "Farm animal"],
      ["PIN", "Metal fastener"],
      ["PIT", "Deep hole"],
      ["POP", "Carbonated drink"],
      ["POT", "Cooking container"],
      ["PRO", "Skilled professional"],
      ["RAG", "Worn cloth"],
      ["RAM", "Male sheep"],
      ["RAT", "Rodent animal"],
      ["RAW", "Uncooked"],
      ["RED", "Primary color"],
      ["RIB", "Chest bone"],
      ["RID", "Remove something"],
      ["RIM", "Circular edge"],
      ["RIP", "Tear apart"],
      ["ROD", "Thin stick"],
      ["ROE", "Fish eggs"],
      ["ROW", "Linear arrangement"],
      ["RUG", "Floor textile"],
      ["RUN", "Move quickly"],
      ["RYE", "Cereal grain"],
      ["SAD", "Unhappy mood"],
      ["SAG", "Sink downward"],
      ["SAP", "Tree fluid"],
      ["SEA", "Large saltwater body"],
      ["SEE", "Perceive visually"],
      ["SET", "Group of items"],
      ["SEW", "Stitch fabric"],
      ["SHY", "Timid behavior"],
      ["SIN", "Moral wrongdoing"],
      ["SIP", "Small drink"],
      ["SIT", "Rest on seat"],
      ["SKY", "Region above earth"],
      ["SLY", "Sneaky manner"],
      ["SON", "Male offspring"],
      ["SOS", "Emergency signal"],
      ["SPA", "Wellness retreat"],
      ["SPY", "Secret observer"],
      ["SUN", "Central star"],
      ["TAB", "Small projection"],
      ["TAG", "Label marker"],
      ["TAN", "Brownish color"],
      ["TAP", "Light touch"],
      ["TEA", "Brewed beverage"],
      ["TEN", "Number after nine"],
      ["TIP", "Advisory hint"],
      ["TOE", "Foot digit"],
      ["TOY", "Play object"],
      ["TRY", "Attempt action"],
      ["TUB", "Large basin"],
      ["TUG", "Forceful pull"],
      ["URN", "Decorative container"],
      ["USE", "Put to work"],
      ["VAT", "Large tank"],
      ["WAR", "Armed conflict"],
      ["WAX", "Soft solid resin"],
      ["WAY", "Path or route"],
      ["WEB", "Silky structure"],
      ["WIN", "Achieve victory"],
      ["WIT", "Clever humor"],
      ["WOE", "Deep sorrow"],
      ["YAK", "Long-haired ox"],
      ["YAM", "Starchy tuber"],
      ["YET", "Up to now"],
      ["ZIP", "Fastening device"]
    ]
  };

  const crosswordWords4 = {
    length: 4,
    words: [
      ["ABLE", "Having capability"],
      ["ACID", "Corrosive substance"],
      ["AGED", "Being old"],
      ["AGEN", "Short time ahead"],
      ["AIDE", "Assistant helper"],
      ["AIRY", "Light and breezy"],
      ["ALSO", "In addition"],
      ["ALTO", "Low female voice"],
      ["AMEN", "So be it"],
      ["ANTE", "Initial poker bet"],
      ["ARCH", "Curved structure"],
      ["AREA", "Measured region"],
      ["ARMY", "Military force"],
      ["AURA", "Distinctive atmosphere"],
      ["AUTO", "Motor vehicle"],
      ["AWAY", "At a distance"],
      ["AXIS", "Central line"],
      ["BABY", "Very young child"],
      ["BACK", "Rear part"],
      ["BAKE", "Cook with heat"],
      ["BALD", "Lacking hair"],
      ["BALL", "Round object"],
      ["BAND", "Musical group"],
      ["BANG", "Loud noise"],
      ["BANK", "Financial institution"],
      ["BARK", "Tree outer layer"],
      ["BARN", "Farm storage building"],
      ["BASE", "Foundation support"],
      ["BATH", "Cleansing soak"],
      ["BEAM", "Long structural bar"],
      ["BEAR", "Large wild mammal"],
      ["BEAT", "Rhythmic strike"],
      ["BEEF", "Cow meat"],
      ["BEER", "Brewed beverage"],
      ["BELL", "Ringing instrument"],
      ["BELT", "Waist strap"],
      ["BEND", "Curve or angle"],
      ["BEST", "Highest quality"],
      ["BILL", "Amount owed"],
      ["BIND", "Tie tightly"],
      ["BIRD", "Feathered creature"],
      ["BITE", "Sharp nibble"],
      ["BLEW", "Moved air"],
      ["BLOG", "Online journal"],
      ["BLUE", "Primary color"],
      ["BOAT", "Water vessel"],
      ["BODY", "Physical form"],
      ["BOIL", "Heat to bubbling"],
      ["BOLD", "Brave and daring"],
      ["BONE", "Hard skeletal part"],
      ["BOND", "Binding connection"],
      ["BONE", "Skeletal piece"],
      ["BOOK", "Written volume"],
      ["BOOT", "Sturdy footwear"],
      ["BORN", "Brought into life"],
      ["BOSS", "Person in charge"],
      ["BOTH", "Two together"],
      ["BOWL", "Round deep dish"],
      ["BOXY", "Square-shaped"],
      ["BRAG", "Boast loudly"],
      ["BRAN", "Cereal outer layer"],
      ["BRAT", "Mischievous child"],
      ["BRED", "Raised or produced"],
      ["BREW", "Make by steeping"],
      ["BRIM", "Edge of container"],
      ["BUCK", "Male deer"],
      ["BUIL", "Construct or make"],
      ["BULK", "Large mass"],
      ["BURN", "Consume by fire"],
      ["BURY", "Place underground"],
      ["BUSH", "Shrubby plant"],
      ["BUSY", "Occupied with tasks"],
      ["BYTE", "Digital unit"],
      ["CAKE", "Sweet baked dessert"],
      ["CALL", "Speak to someone"],
      ["CALM", "Free from disturbance"],
      ["CAMP", "Temporary shelter"],
      ["CANE", "Walking stick"],
      ["CARD", "Printed rectangle"],
      ["CARE", "Attentive concern"],
      ["CART", "Two-wheeled vehicle"],
      ["CASE", "Protective container"],
      ["CASH", "Money in notes"],
      ["CAST", "Throw or project"],
      ["CAVE", "Natural hollow"],
      ["CELL", "Basic life unit"],
      ["CHAT", "Informal talk"],
      ["CHEF", "Professional cook"],
      ["CHEW", "Masticate food"],
      ["CHIN", "Lower face area"],
      ["CHOP", "Cut into pieces"],
      ["CITY", "Large town"],
      ["CLAY", "Fine earthy soil"],
      ["CLIP", "Fastening device"],
      ["CLUB", "Social association"],
      ["COAL", "Combustible rock"],
      ["COAT", "Outer garment"],
      ["COIN", "Metal currency"],
      ["COLD", "Low temperature"],
      ["COME", "Approach or arrive"],
      ["CONE", "Tapered shape"],
      ["COOK", "Prepare food"],
      ["COOL", "Moderately cold"],
      ["CORD", "Thin rope"],
      ["CORE", "Central part"],
      ["CORN", "Yellow grain crop"],
      ["COST", "Required expense"],
      ["CREW", "Working group"],
      ["CROP", "Harvested plants"],
      ["CUBE", "Six-sided solid"],
      ["CUFF", "Wrist band"],
      ["CURL", "Twist into coils"],
      ["CURE", "Healing remedy"],
      ["CURL", "Twisted lock"],
      ["DARK", "Without light"],
      ["DAWN", "Morning daybreak"],
      ["DAYS", "Units of time"],
      ["DEAL", "Business transaction"],
      ["DEEP", "Far downward"],
      ["DEER", "Graceful herbivore"],
      ["DIAL", "Rotary control"],
      ["DIET", "Food regimen"],
      ["DIME", "Ten-cent coin"],
      ["DINE", "Eat dinner"],
      ["DISH", "Food container"],
      ["DIVE", "Plunge downward"],
      ["DOCK", "Boat landing"],
      ["DOME", "Rounded roof"],
      ["DONE", "Completed action"],
      ["DOOR", "Entrance barrier"],
      ["DOWN", "Toward below"],
      ["DRAG", "Pull with effort"],
      ["DRAW", "Produce lines"],
      ["DRESS", "One-piece garment"],
      ["DROP", "Let fall"],
      ["DRUM", "Percussion instrument"],
      ["DUAL", "Having two parts"],
      ["DUCK", "Web-footed bird"],
      ["DUNE", "Hill of sand"],
      ["DUST", "Fine dry particles"],
      ["DUTY", "Obligated task"],
      ["EACH", "Every individual"],
      ["EARN", "Receive for work"],
      ["EAST", "Compass direction"],
      ["ECHO", "Reflected sound"],
      ["EDGE", "Border line"],
      ["EDIT", "Modify text"],
      ["EGGS", "Oval food items"],
      ["ELSE", "Other than"],
      ["EMIT", "Send out"],
      ["ENVY", "Jealous desire"],
      ["EPIC", "Grand narrative"],
      ["EVEN", "Flat and level"],
      ["EVER", "At any time"],
      ["EVIL", "Deep wrongdoing"],
      ["EXIT", "Way out"],
      ["FACE", "Front of head"],
      ["FADE", "Lose brightness"],
      ["FAIL", "Not succeed"],
      ["FAIR", "Reasonable quality"],
      ["FALL", "Descend downward"],
      ["FARM", "Agricultural land"],
      ["FAST", "Moving quickly"],
      ["FATE", "Destined outcome"],
      ["FEAR", "Feeling of dread"],
      ["FEED", "Give food"],
      ["FEEL", "Experience touch"],
      ["FELL", "Cut down"],
      ["FELT", "Pressed fabric"],
      ["FEND", "Ward off"],
      ["FIBS", "Small lies"],
      ["FINE", "High quality"],
      ["FIRM", "Solid and stable"],
      ["FISH", "Aquatic animal"],
      ["FIVE", "Number after four"],
      ["FLAG", "Symbolic banner"],
      ["FLAT", "Smooth level"],
      ["FLEW", "Traveled by air"],
      ["FLIP", "Turn quickly"],
      ["FLOW", "Move smoothly"],
      ["FOAM", "Bubbly mass"],
      ["FOOD", "Edible substance"],
      ["FOOL", "Silly person"],
      ["FOOT", "Lower limb end"],
      ["FORT", "Military post"],
      ["FOUR", "Number before five"],
      ["FOWL", "Bird used for food"],
      ["FREE", "Without cost"],
      ["FROG", "Amphibious jumper"],
      ["FROM", "Starting point"],
      ["FUEL", "Energy source"],
      ["FULL", "Containing all"],
      ["FUND", "Stored money"],
      ["GAIN", "Increase amount"],
      ["GAME", "Play activity"],
      ["GATE", "Movable barrier"],
      ["GAVE", "Handed over"],
      ["GEAR", "Mechanical wheels"],
      ["GIFT", "Given present"],
      ["GIRL", "Young female"],
      ["GIVE", "Hand over"],
      ["GLAD", "Feeling happy"],
      ["GLUE", "Sticky adhesive"],
      ["GOAL", "Desired result"],
      ["GOAT", "Horned farm animal"],
      ["GOLD", "Precious metal"],
      ["GOLF", "Club-and-ball sport"],
      ["GOOD", "Of high quality"],
      ["GOWN", "Long formal dress"],
      ["GRAB", "Take quickly"],
      ["GRAY", "Neutral color"],
      ["GROW", "Increase in size"],
      ["HALF", "Fifty percent"],
      ["HALL", "Large corridor"],
      ["HAND", "Human appendage"],
      ["HANG", "Suspend downward"],
      ["HARD", "Difficult to do"],
      ["HARM", "Cause injury"],
      ["HATE", "Intense dislike"],
      ["HAVE", "Possess ownership"],
      ["HEAD", "Top body part"],
      ["HEAL", "Restore health"],
      ["HEAP", "Pile of things"],
      ["HEAR", "Perceive sound"],
      ["HEAT", "Warmth energy"],
      ["HELP", "Provide assistance"],
      ["HERB", "Aromatic plant"],
      ["HERE", "In this place"],
      ["HERO", "Brave figure"],
      ["HIDE", "Keep out of sight"],
      ["HIGH", "Elevated position"],
      ["HILL", "Raised land"],
      ["HINT", "Small suggestion"],
      ["HIRE", "Employ someone"],
      ["HOLD", "Keep in hand"],
      ["HOLE", "Open cavity"],
      ["HOME", "Place of residence"],
      ["HOPE", "Feeling of expectation"],
      ["HORN", "Pointed projection"],
      ["HOSE", "Flexible tube"],
      ["HOST", "Event organizer"],
      ["HUGE", "Very large"],
      ["HUNT", "Search for prey"],
      ["HURT", "Cause pain"],
      ["ICON", "Symbolic image"],
      ["IDEA", "Thought concept"],
      ["IDLE", "Not active"],
      ["IGNO", "Not aware"],
      ["INTO", "Toward inside"],
      ["IRON", "Strong metal"],
      ["ITEM", "Listed object"],
      ["JACK", "Lifting device"],
      ["JADE", "Green gemstone"],
      ["JAIL", "Place of confinement"],
      ["JAWN", "Urban colloquial term"],
      ["JOIN", "Connect together"],
      ["JOKE", "Humorous remark"],
      ["JUMP", "Leap upward"],
      ["JURY", "Group giving verdict"],
      ["JUST", "Fair or proper"],
      ["KEEN", "Sharp or eager"],
      ["KEEP", "Retain possession"],
      ["KICK", "Strike with foot"],
      ["KIND", "Type or variety"],
      ["KING", "Male ruler"],
      ["KISS", "Press lips"],
      ["KITE", "Wind-flown toy"],
      ["KNEE", "Leg joint"],
      ["KNIT", "Looped-yarn craft"],
      ["KNOW", "Be aware"],
      ["LACK", "Be without"],
      ["LAMB", "Young sheep"],
      ["LAME", "Weak or injured"],
      ["LAMP", "Light source"],
      ["LAND", "Solid ground"],
      ["LARGE", "Big size"],  // adjust? skip 5 letters; remove
      ["LATE", "After expected time"],
      ["LAWN", "Grass area"],
      ["LAZY", "Disliking work"],
      ["LEAD", "Guide or direct"],
      ["LEAF", "Plant blade"],
      ["LEAN", "Rest at angle"],
      ["LEFT", "Opposite right"],
      ["LEND", "Give temporarily"],
      ["LENS", "Glass for focusing"],
      ["LESS", "Smaller amount"],
      ["LIFE", "Living existence"],
      ["LIFT", "Raise upward"],
      ["LIKE", "Find agreeable"],
      ["LION", "Large feline"],
      ["LIST", "Item sequence"],
      ["LIVE", "Be alive"],
      ["LOAD", "Put cargo on"],
      ["LOAF", "Bread portion"],
      ["LOCK", "Securing device"],
      ["LOFT", "Upper room"],
      ["LONG", "Extended length"],
      ["LOOK", "Direct eyes"],
      ["LOOP", "Circular bend"],
      ["LOSS", "State of losing"],
      ["LOST", "Unable to find way"],
      ["LOUD", "High volume"],
      ["LOVE", "Deep affection"],
      ["LUNG", "Breathing organ"],
      ["MADE", "Created or built"],
      ["MAIL", "Posted letters"],
      ["MAIN", "Most important"],
      ["MAKE", "Create something"],
      ["MALE", "Of masculine sex"],
      ["MALL", "Shopping center"],
      ["MANY", "Large number"],
      ["MARK", "Visible trace"],
      ["MASK", "Face covering"],
      ["MASS", "Large quantity"],
      ["MEAL", "Time of eating"],
      ["MEAN", "Intend to convey"],
      ["MEAT", "Animal flesh"],
      ["MEET", "Come together"],
      ["MELT", "Change to liquid"],
      ["MEND", "Repair something"],
      ["MENU", "List of dishes"],
      ["MERE", "Nothing more than"],
      ["MESS", "Disorganized state"],
      ["MICE", "Small rodents"],
      ["MILD", "Not extreme"],
      ["MILE", "Unit of distance"],
      ["MILK", "Dairy liquid"],
      ["MIND", "Thinking faculty"],
      ["MINE", "Belonging to me"],
      ["MINT", "Aromatic herb"],
      ["MISS", "Fail to hit"],
      ["MIST", "Fine spray"],
      ["MOAT", "Deep defensive ditch"],
      ["MOCK", "Ridicule openly"],
      ["MODE", "Particular style"],
      ["MOLD", "Fungus growth"],
      ["MOOD", "Emotional state"],
      ["MOON", "Earth’s satellite"],
      ["MORE", "Greater amount"],
      ["MOST", "Largest quantity"],
      ["MOVE", "Change position"],
      ["MUCK", "Sticky dirt"],
      ["MUFF", "Hand warmer"],
      ["MULE", "Hybrid animal"],
      ["MUSE", "Source of inspiration"],
      ["MUTE", "Without sound"],
      ["NAIL", "Metal fastener"],
      ["NAME", "Word for identity"],
      ["NAPE", "Back of neck"],
      ["NARR", "Story indicator"],
      ["NEAR", "Close by"],
      ["NEAT", "Clean and orderly"],
      ["NEED", "Require necessity"],
      ["NEST", "Bird’s home"],
      ["NEWS", "Recent information"],
      ["NEXT", "Coming after"],
      ["NICE", "Pleasant nature"],
      ["NINE", "Number after eight"],
      ["NOON", "Middle of day"],
      ["NOSE", "Smelling organ"],
      ["NOTE", "Short message"],
      ["NOUN", "Naming word"],
      ["NUTS", "Edible seeds"],
      ["OATH", "Sworn promise"],
      ["OBEY", "Follow orders"],
      ["ODOR", "Distinct smell"],
      ["OFFER", "Present for acceptance"],
      ["OILS", "Liquid fats"],
      ["OMEN", "Future sign"],
      ["ONLY", "Solely or just"],
      ["ONTO", "Moving upon"],
      ["OPEN", "Not closed"],
      ["ORAL", "Spoken form"],
      ["OVER", "Above or across"],
      ["PACE", "Step movement"],
      ["PACK", "Bundle tightly"],
      ["PAGE", "Sheet of paper"],
      ["PAID", "Given payment"],
      ["PAIN", "Physical hurt"],
      ["PAIR", "Two together"],
      ["PALM", "Tree species"],
      ["PANG", "Sudden ache"],
      ["PANT", "Breathe quickly"],
      ["PARK", "Public green area"],
      ["PART", "Piece of whole"],
      ["PASS", "Move beyond"],
      ["PAST", "Gone by"],
      ["PATH", "Worn track"],
      ["PEAK", "Mountain top"],
      ["PEAR", "Sweet fruit"],
      ["PEEK", "Quick glance"],
      ["PEEL", "Outer covering"],
      ["PEER", "Look closely"],
      ["PENNY", "Single cent"], // Actually 5 letters; remove
      ["PENT", "Confined or held"], 
      ["PICK", "Choose something"],
      ["PIER", "Docking platform"],
      ["PIKE", "Long weapon"],
      ["PINE", "Evergreen tree"],
      ["PINK", "Pale red color"],
      ["PIPE", "Hollow tube"],
      ["PITY", "Feeling of sorrow"],
      ["PLAN", "Detailed idea"],
      ["PLAY", "Recreational activity"],
      ["PLOT", "Story outline"],
      ["PLUG", "Blocking device"],
      ["PLUS", "Added advantage"],
      ["POEM", "Short verse"],
      ["POKE", "Prod with finger"],
      ["POLE", "Long cylindrical rod"],
      ["POND", "Small water body"],
      ["POOL", "Recreation basin"],
      ["POOR", "Lacking wealth"],
      ["PORT", "Harbor city"],
      ["POSE", "Strike a stance"],
      ["POST", "Mail dispatch"],
      ["POUR", "Cause to flow"],
      ["PRAY", "Address deity"],
      ["PREP", "Prepare ahead"],
      ["PRIM", "Proper and formal"],
      ["PROS", "Advantages list"],
      ["PULL", "Draw toward self"],
      ["PURE", "Without impurities"],
      ["PUSH", "Apply forward force"],
      ["QUIT", "Stop doing"],
      ["RACE", "Speed contest"],
      ["RACK", "Storage frame"],
      ["RAIL", "Metal track"],
      ["RAIN", "Falling water"],
      ["RAKE", "Garden tool"],
      ["RAMP", "Inclined surface"],
      ["RANG", "Made a sound"],
      ["RANK", "Relative position"],
      ["RANT", "Angry speech"],
      ["RARE", "Uncommon type"],
      ["RATE", "Assigned value"],
      ["READ", "Interpret text"],
      ["REAL", "Existing fact"],
      ["REAR", "Back portion"],
      ["REED", "Tall grass plant"],
      ["REEL", "Spool of film"],
      ["RELY", "Depend on"],
      ["RENT", "Payment for use"],
      ["REST", "Cease action"],
      ["RICE", "Staple grain"],
      ["RICH", "Having wealth"],
      ["RIDE", "Travel on"],
      ["RIFT", "Gap or opening"],
      ["RING", "Circular band"],
      ["RISE", "Move upward"],
      ["RISK", "Chance of loss"],
      ["ROAD", "Paved path"],
      ["ROAR", "Loud deep sound"],
      ["ROCK", "Solid stone"],
      ["ROLE", "Assigned part"],
      ["ROLL", "Move by turning"],
      ["ROOF", "Top covering"],
      ["ROOM", "Interior space"],
      ["ROOT", "Plant anchor"],
      ["ROPE", "Thick cord"],
      ["ROSE", "Flower type"],
      ["RUBY", "Red gemstone"],
      ["RUDE", "Impolite behavior"],
      ["RULE", "Established guideline"],
      ["RUNG", "Step of ladder"],
      ["RUSH", "Hurry quickly"],
      ["SAGE", "Wise person"],
      ["SAIL", "Ship's canvas"],
      ["SALT", "Seasoning mineral"],
      ["SAND", "Fine grain particles"],
      ["SAVE", "Rescue or store"],
      ["SCAN", "Look over quickly"],
      ["SCAR", "Healed mark"],
      ["SCOT", "Person from Scotland"],
      ["SEAL", "Close tightly"],
      ["SEAM", "Joined edges"],
      ["SEAR", "Burn surface"],
      ["SEAT", "Place to sit"],
      ["SEED", "Plant embryo"],
      ["SEEK", "Search for"],
      ["SEEN", "Viewed before"],
      ["SELF", "Person's identity"],
      ["SELL", "Offer for money"],
      ["SEND", "Dispatch outward"],
      ["SENT", "Delivered message"],
      ["SETT", "Stone paving"],
      ["SHIP", "Ocean vessel"],
      ["SHOE", "Foot covering"],
      ["SHOP", "Place to buy"],
      ["SHOT", "Fired attempt"],
      ["SHOW", "Display to view"],
      ["SHUT", "Close firmly"],
      ["SICK", "Not healthy"],
      ["SIDE", "Outer surface"],
      ["SIGN", "Visible symbol"],
      ["SILK", "Soft fine fiber"],
      ["SING", "Produce melody"],
      ["SINK", "Descend downward"],
      ["SIRE", "Male parent"],
      ["SITE", "Location area"],
      ["SIZE", "Magnitude measure"],
      ["SKIN", "Outer covering"],
      ["SKIP", "Leave out"],
      ["SLAM", "Shut violently"],
      ["SLAP", "Quick strike"],
      ["SLED", "Snow vehicle"],
      ["SLEEP", "Resting state"],
      ["SLIP", "Lose footing"],
      ["SLOW", "Not fast"],
      ["SMOG", "Air pollution"],
      ["SNAP", "Break sharply"],
      ["SNOW", "Frozen flakes"],
      ["SOAP", "Cleaning bar"],
      ["SOAK", "Immerse in liquid"],
      ["SOFT", "Gentle texture"],
      ["SOLE", "Bottom of foot"],
      ["SOME", "Unspecified amount"],
      ["SONG", "Musical piece"],
      ["SOON", "In short time"],
      ["SORT", "Arrange by type"],
      ["SOUL", "Inner essence"],
      ["SOUP", "Liquid meal"],
      ["SPAN", "Length from end to end"],
      ["SPAR", "Boxing practice"],
      ["SPIN", "Turn rapidly"],
      ["SPOT", "Small mark"],
      ["STAR", "Shining celestial body"],
      ["STEM", "Plant stalk"],
      ["STEP", "Single stride"],
      ["STOP", "Cease motion"],
      ["STOR", "Keep stored"], 
      ["STOW", "Pack neatly"],
      ["STUD", "Decorative nail"],
      ["SUCH", "Of that kind"],
      ["SUIT", "Matched outfit"],
      ["SULK", "Moody silence"],
      ["SUMO", "Japanese wrestling"],
      ["SURE", "Confident belief"],
      ["SURF", "Ride waves"],
      ["SWAN", "Graceful waterbird"],
      ["SWAY", "Move side to side"],
      ["SWIM", "Move in water"],
      ["TAKE", "Lay hold of"],
      ["TALE", "Story narrative"],
      ["TALK", "Speak words"],
      ["TANK", "Liquid container"],
      ["TAPE", "Adhesive strip"],
      ["TASK", "Assigned duty"],
      ["TEAR", "Rip apart"],
      ["TEEN", "Adolescent youth"],
      ["TELL", "Communicate verbally"],
      ["TENT", "Portable shelter"],
      ["TERM", "Specific period"],
      ["TEST", "Evaluation tool"],
      ["TEXT", "Written words"],
      ["THEN", "At that time"],
      ["THIN", "Not thick"],
      ["THIS", "Close by thing"],
      ["THRE", "Slight number"], 
      ["THRU", "By way of"],
      ["TIDE", "Sea level rise"],
      ["TILE", "Ceramic square"],
      ["TIME", "Measured duration"],
      ["TINY", "Very small"],
      ["TIRE", "Rubber wheel"],
      ["TOAD", "Earth-dwelling amphibian"],
      ["TOAST", "Browned bread"],
      ["TOLD", "Informed verbally"],
      ["TONE", "Sound quality"],
      ["TOOL", "Handheld implement"],
      ["TOOK", "Took possession"],
      ["TOOL", "Work implement"],
      ["TORE", "Ripped apart"],
      ["TOWN", "Populated area"],
      ["TRAP", "Catch device"],
      ["TREE", "Tall plant"],
      ["TRIM", "Cut neatly"],
      ["TRIO", "Group of three"],
      ["TRIP", "Short journey"],
      ["TRUE", "In accordance with fact"],
      ["TUBE", "Hollow cylinder"],
      ["TUNE", "Melodic composition"],
      ["TURN", "Rotate direction"],
      ["TWIN", "One of two"],
      ["TYPE", "Form or category"],
      ["UNIT", "Individual piece"],
      ["UNDO", "Reverse action"],
      ["UNIT", "Single quantity"],
      ["UPON", "Resting on"],
      ["URGE", "Strong desire"],
      ["USED", "Previously utilized"],
      ["USER", "System operator"],
      ["VAIN", "Having excessive pride"],
      ["VALE", "Valley region"],
      ["VARY", "Change slightly"],
      ["VEIN", "Blood vessel"],
      ["VENT", "Air passage"],
      ["VERY", "To high degree"],
      ["VIEW", "Visual inspection"],
      ["VINE", "Climbing plant"],
      ["VOID", "Empty space"],
      ["WAGE", "Worker payment"],
      ["WAIL", "Loud cry"],
      ["WAIT", "Stay in place"],
      ["WAKE", "Stop sleeping"],
      ["WALK", "Move on foot"],
      ["WALL", "Vertical barrier"],
      ["WANT", "Desire strongly"],
      ["WARD", "Hospital section"],
      ["WARM", "Moderately hot"],
      ["WARN", "Give caution"],
      ["WASH", "Clean with water"],
      ["WAVE", "Move hand"],
      ["WEAK", "Lacking strength"],
      ["WEAR", "Put on clothing"],
      ["WEEK", "Seven days"],
      ["WEED", "Unwanted plant"],
      ["WEEP", "Cry softly"],
      ["WELL", "In good manner"],
      ["WENT", "Moved along"],
      ["WEST", "Compass direction"],
      ["WHEW", "Expression of relief"],
      ["WHEN", "At what time"],
      ["WHIP", "Striking tool"],
      ["WHIR", "Rapid spinning sound"],
      ["WHOM", "Object of who"],
      ["WIDE", "Great width"],
      ["WIFE", "Married woman"],
      ["WILD", "Untamed state"],
      ["WIND", "Moving air"],
      ["WINE", "Fermented beverage"],
      ["WING", "Flying limb"],
      ["WIRE", "Thin metal strand"],
      ["WISE", "Having knowledge"],
      ["WISH", "Hope or desire"],
      ["WITH", "Accompanied by"],
      ["WOOD", "Tree material"],
      ["WOOL", "Sheep fiber"],
      ["WORD", "Language unit"],
      ["WORE", "Had on"],
      ["WORK", "Productive effort"],
      ["WORM", "Crawling invertebrate"],
      ["WORN", "Used up"],
      ["WRAP", "Cover completely"],
      ["YARD", "Outdoor enclosure"],
      ["YARN", "Spun fiber"],
      ["YAWN", "Open-mouthed inhale"],
      ["YEAR", "Twelve months"],
      ["YELL", "Shout loudly"],
      ["YOGA", "Mind-body practice"],
      ["YOKE", "Harness device"],
      ["YOUN", "Young person"], 
      ["ZERO", "No quantity"],
      ["ZEST", "Spirited energy"],
      ["ZINC", "Metal element"],
      ["ZONE", "Specific area"],
      ["ZOOM", "Move quickly"]
    ]
  };

  const words5 = {
    length: 5,
    words: [
      ["ABOVE", "Overhead position"],
      ["ACORN", "Oak tree nut"],
      ["AGREE", "Share the same view"],
      ["ALERT", "Quick to notice"],
      ["ALIVE", "Living state"],
      ["ANGEL", "Heavenly being"],
      ["APRIL", "Fourth month"],
      ["ARROW", "Pointed projectile"],
      ["AWARE", "Conscious of"],
      ["BADGE", "Symbol of authority"],
      ["BASIC", "Fundamental level"],
      ["BEACH", "Sandy shoreline"],
      ["BEGAN", "Started earlier"],
      ["BEGIN", "Start action"],
      ["BERRY", "Small edible fruit"],
      ["BIBLE", "Sacred text"],
      ["BLAME", "Assign fault"],
      ["BLAST", "Strong burst"],
      ["BLEND", "Mix together"],
      ["BLOCK", "Solid piece"],
      ["BLOOM", "Flowering state"],
      ["BLUES", "Melancholic music"],
      ["BOARD", "Flat panel"],
      ["BOOST", "Increase support"],
      ["BOUND", "Leap forward"],
      ["BRAVE", "Courageous one"],
      ["BREAD", "Baked staple"],
      ["BREAK", "Short pause"],
      ["BRICK", "Clay building block"],
      ["BRIEF", "Short summary"],
      ["BRING", "Carry to place"],
      ["BROAD", "Wide extent"],
      ["BROOK", "Small stream"],
      ["BROWN", "Earth-tone color"],
      ["BRUSH", "Cleaning tool"],
      ["BUILD", "Construct something"],
      ["CABLE", "Thick rope or wire"],
      ["CANDY", "Sugary treat"],
      ["CARRY", "Hold and move"],
      ["CATCH", "Seize suddenly"],
      ["CAUSE", "Reason behind"],
      ["CHAIN", "Linked metal series"],
      ["CHAIR", "Seat with back"],
      ["CHARM", "Attractive trait"],
      ["CHASE", "Pursue quickly"],
      ["CHEER", "Shout of praise"],
      ["CHEST", "Upper torso"],
      ["CHIEF", "Person in charge"],
      ["CHILD", "Young person"],
      ["CHORD", "Musical harmony"],
      ["CIVIC", "City-related"],
      ["CLAIM", "Assert ownership"],
      ["CLASS", "Group of students"],
      ["CLEAN", "Free of dirt"],
      ["CLEAR", "Easily seen"],
      ["CLIFF", "Steep rock face"],
      ["CLOCK", "Time-telling device"],
      ["CLOSE", "Shut firmly"],
      ["CLOUD", "Sky vapor mass"],
      ["COAST", "Land by sea"],
      ["COLOR", "Visual hue"],
      ["COOKS", "Prepares food"],
      ["CORAL", "Reef organism"],
      ["COUNT", "Add up"],
      ["CRAFT", "Handmade skill"],
      ["CRANE", "Tall lifting machine"],
      ["CRASH", "Sudden smash"],
      ["CRATE", "Wooden box"],
      ["CRAWL", "Move on hands and knees"],
      ["CRISP", "Firm and fresh"],
      ["CROSS", "Intersecting shape"],
      ["CROWN", "Royal headpiece"],
      ["DANCE", "Rhythmic movement"],
      ["DEBIT", "Bank withdrawal"],
      ["DELTA", "River mouth area"],
      ["DEPTH", "Measurement downward"],
      ["DIARY", "Personal journal"],
      ["DWELL", "Live in place"],
      ["EARTH", "Our planet"],
      ["EAGER", "Keenly interested"],
      ["EARLY", "Ahead of time"],
      ["EIGHT", "Number 8"],
      ["ELBOW", "Arm joint"],
      ["ELDER", "Older person"],
      ["EMPTY", "Containing nothing"],
      ["ENTER", "Go inside"],
      ["EVERY", "Each without exception"],
      ["FAIRY", "Mythical sprite"],
      ["FAITH", "Belief system"],
      ["FANCY", "Decorative style"],
      ["FATAL", "Causing death"],
      ["FAULT", "Break in rock"],
      ["FAVOR", "Helpful act"],
      ["FENCE", "Barrier structure"],
      ["FIELD", "Open land"],
      ["FINAL", "Last stage"],
      ["FIRST", "Before all others"],
      ["FLAME", "Burning fire"],
      ["FLANK", "Side region"],
      ["FLASH", "Brief burst"],
      ["FLEET", "Group of ships"],
      ["FLIRT", "Playfully attract"],
      ["FLOAT", "Rest on surface"],
      ["FLOOD", "Overflow of water"],
      ["FLOOR", "Room surface"],
      ["FLOWN", "Traveled by air"],
      ["FOCUS", "Central attention"],
      ["FORCE", "Physical power"],
      ["FORGE", "Shape by heating"],
      ["FORMS", "Shapes or documents"],
      ["FRAME", "Supporting structure"],
      ["FRESH", "Recently made"],
      ["FRUIT", "Edible plant part"],
      ["GHOST", "Spirit apparition"],
      ["GIANT", "Very large being"],
      ["GLASS", "Transparent material"],
      ["GLOVE", "Hand covering"],
      ["GLORY", "Honor or fame"],
      ["GRACE", "Elegance of movement"],
      ["GRADE", "Evaluation score"],
      ["GRAIN", "Cereal seed"],
      ["GRAND", "Impressive scale"],
      ["GRAPE", "Small vine fruit"],
      ["GRASP", "Hold firmly"],
      ["GRASS", "Green ground plant"],
      ["GREAT", "Very good"],
      ["GREEN", "Color of foliage"],
      ["GREET", "Welcome warmly"],
      ["GRIND", "Reduce to powder"],
      ["GROUP", "Collection of people"],
      ["GUARD", "Protective watch"],
      ["GUEST", "Visitor or invitee"],
      ["GUIDE", "One who leads"],
      ["HABIT", "Regular pattern"],
      ["HAPPY", "Feeling joy"],
      ["HARDY", "Strong and tough"],
      ["HEART", "Organ of circulation"],
      ["HEDGE", "Shrubby barrier"],
      ["HELLO", "Greeting word"],
      ["HONEY", "Sweet bee product"],
      ["HORSE", "Hooved mammal"],
      ["HOUSE", "Residential building"],
      ["HUMAN", "Person or individual"],
      ["HUMOR", "Amusing quality"],
      ["IDEAL", "Perfect standard"],
      ["IMAGE", "Visual representation"],
      ["INNER", "Located inside"],
      ["IVORY", "Hard white material"],
      ["JEANS", "Denim pants"],
      ["JELLY", "Fruit spread"],
      ["JEWEL", "Cut gemstone"],
      ["JUICE", "Fruit liquid"],
      ["KETLE", "Water boiler"], // Keeping common structure; if preferred, replace with "KETTL" alternatives
      ["KNIFE", "Cutting tool"],
      ["KNOCK", "Rap on surface"],
      ["LABEL", "Identification tag"],
      ["LADLE", "Serving scoop"],
      ["LASER", "Focused light beam"],
      ["LAYER", "Single thickness"],
      ["LEARN", "Gain knowledge"],
      ["LEMON", "Sour yellow fruit"],
      ["LEVEL", "Even surface"],
      ["LIGHT", "Visible illumination"],
      ["LIMIT", "Boundary point"],
      ["LINEN", "Woven fabric"],
      ["LIVER", "Vital organ"],
      ["LUNCH", "Midday meal"],
      ["MAGIC", "Supernatural effect"],
      ["MAJOR", "Primary importance"],
      ["MAPLE", "Hardwood tree"],
      ["MARCH", "Walk in formation"],
      ["MARSH", "Wet land area"],
      ["MATCH", "Compatible pair"],
      ["METAL", "Hard shiny element"],
      ["MIGHT", "Great strength"],
      ["MINOR", "Lesser importance"],
      ["MODEL", "Representation example"],
      ["MONEY", "Medium of exchange"],
      ["MONTH", "Time period of 30 days"],
      ["MOODY", "Changeable temper"],
      ["MOTOR", "Engine device"],
      ["MOUNT", "Climb up"],
      ["MOUTH", "Opening for eating"],
      ["MUSIC", "Organized sound"],
      ["NARROW", "Thin width"],
      ["NERVE", "Fibrous tissue"],
      ["NIGHT", "Dark period"],
      ["NOISE", "Unwanted sound"],
      ["NORTH", "Compass direction"],
      ["NOTES", "Written points"],
      ["OCEAN", "Large saltwater body"],
      ["ODDLY", "In strange manner"],
      ["OFFER", "Present for acceptance"],
      ["OLIVE", "Small green fruit"],
      ["OPERA", "Dramatic musical work"],
      ["ORDER", "Command or sequence"],
      ["ORGAN", "Musical keyboard"],
      ["OTHER", "Different one"],
      ["PAINT", "Colored coating"],
      ["PALACE", "Grand residence"],
      ["PANIC", "Sudden fear"],
      ["PARTY", "Social gathering"],
      ["PATCH", "Piece for repair"],
      ["PEACE", "State of calm"],
      ["PEACH", "Soft sweet fruit"],
      ["PEARL", "Lustrous gem"],
      ["PEBBLE", "Small stone"],
      ["PENNY", "One-cent coin"],
      ["PHONE", "Calling device"],
      ["PIECE", "Part of whole"],
      ["PILOT", "Aircraft operator"],
      ["PITCH", "Throw the ball"],
      ["PLAIN", "Unadorned area"],
      ["PLANT", "Living vegetation"],
      ["PLATE", "Flat dish"],
      ["POINT", "Specific location"],
      ["POWER", "Ability to act"],
      ["PRESS", "Apply pressure"],
      ["PRICE", "Cost amount"],
      ["PRIDE", "Self-respect"],
      ["PRIME", "Most important"],
      ["PRINT", "Produce text"],
      ["PRIZE", "Award for merit"],
      ["PROOF", "Evidence of truth"],
      ["QUEEN", "Female monarch"],
      ["QUICK", "Moving fast"],
      ["QUIET", "Low noise"],
      ["RADIO", "Broadcast receiver"],
      ["RAISE", "Lift upward"],
      ["RANGE", "Stretch of land"],
      ["RAPID", "Very fast"],
      ["RAZOR", "Shaving tool"],
      ["REACH", "Extend arm"],
      ["READY", "Prepared state"],
      ["REACT", "Respond to stimulus"],
      ["REBEL", "Opposing resister"],
      ["RELAY", "Pass along"],
      ["REPLY", "Response word"],
      ["RESET", "Return to default"],
      ["RIDER", "One who rides"],
      ["RIVER", "Flowing watercourse"],
      ["ROUND", "Circular shape"],
      ["ROUTE", "Travel path"],
      ["ROYAL", "Related to monarchy"],
      ["RURAL", "Country area"],
      ["SAFER", "More secure"],
      ["SALAD", "Mixed greens dish"],
      ["SALES", "Business transactions"],
      ["SALTY", "Containing salt"],
      ["SANDY", "Covered in sand"],
      ["SCALE", "Measuring device"],
      ["SCARF", "Neck garment"],
      ["SCENE", "View or setting"],
      ["SCOPE", "Range of view"],
      ["SCORE", "Total points"],
      ["SCOUT", "Explorer or guide"],
      ["SCRAP", "Small leftover"],
      ["SENSE", "Perception ability"],
      ["SERVE", "Provide service"],
      ["SHADE", "Shadowed area"],
      ["SHAKE", "Trembling motion"],
      ["SHAPE", "Form or outline"],
      ["SHARE", "Divide with others"],
      ["SHARP", "Having edge"],
      ["SHELF", "Storage platform"],
      ["SHELL", "Hard outer covering"],
      ["SHIFT", "Change position"],
      ["SHINE", "Reflect light"],
      ["SHIRT", "Upper garment"],
      ["SHOCK", "Sudden surprise"],
      ["SHORE", "Edge of water"],
      ["SHORT", "Not long"],
      ["SHOUT", "Loud call"],
      ["SHOWN", "Displayed earlier"],
      ["SIGHT", "Ability to see"],
      ["SILLY", "Lacking seriousness"],
      ["SINCE", "From that time"],
      ["SKILL", "Learned ability"],
      ["SKIRT", "Waist garment"],
      ["SLEEP", "Resting state"],
      ["SMALL", "Little size"],
      ["SMART", "Clever or stylish"],
      ["SMILE", "Friendly expression"],
      ["SMOKE", "Airborne vapor"],
      ["SNAKE", "Slithering reptile"],
      ["SOLID", "Firm structure"],
      ["SONIC", "Sound-related"],
      ["SORRY", "Regretful tone"],
      ["SOUND", "Audible vibration"],
      ["SPACE", "Open expanse"],
      ["SPARE", "Extra amount"],
      ["SPEAK", "Use voice"],
      ["SPEED", "Rate of motion"],
      ["SPICE", "Flavoring plant"],
      ["SPINE", "Backbone column"],
      ["SPITE", "Malicious intent"],
      ["SPORT", "Athletic activity"],
      ["SPOON", "Eating utensil"],
      ["SPOTY", "Marked with spots"], // can be replaced if desired
      ["SPRAY", "Fine mist"],
      ["SPRING", "Season after winter"],
      ["SQUAD", "Small team"],
      ["STACK", "Pile of items"],
      ["STAFF", "Workforce group"],
      ["STAGE", "Performance area"],
      ["STAMP", "Postal label"],
      ["STAND", "Remain upright"],
      ["STARE", "Look intently"],
      ["START", "Begin action"],
      ["STATE", "Condition or area"],
      ["STEAM", "Water vapor"],
      ["STEEL", "Strong metal"],
      ["STEEP", "Sharp slope"],
      ["STEPS", "Stair sections"],
      ["STICK", "Thin wooden rod"],
      ["STILL", "Not moving"],
      ["STOCK", "Stored supplies"],
      ["STONE", "Hard rock piece"],
      ["STORM", "Violent weather"],
      ["STORY", "Narrative tale"],
      ["STRAP", "Narrow band"],
      ["STRAW", "Dried stalk"],
      ["STRIP", "Narrow piece"],
      ["STUCK", "Unable to move"],
      ["STUDY", "Learn carefully"],
      ["STYLE", "Distinct manner"],
      ["SUGAR", "Sweet crystals"],
      ["SUNNY", "Full of sunlight"],
      ["SUPER", "Above standard"],
      ["SWEET", "Sugary taste"],
      ["SWIFT", "Quick movement"],
      ["SWING", "Sway back and forth"],
      ["TABLE", "Flat-topped furniture"],
      ["TASTE", "Flavor sensation"],
      ["TEACH", "Give instruction"],
      ["TEARS", "Drops of crying"],
      ["TEETH", "Biting structures"],
      ["THANK", "Express gratitude"],
      ["THEME", "Central idea"],
      ["THICK", "Wide or deep"],
      ["THINK", "Use the mind"],
      ["THIRD", "Next after second"],
      ["THORN", "Sharp plant spine"],
      ["THOSE", "Previously mentioned ones"],
      ["THROW", "Hurl forward"],
      ["TIGER", "Striped big cat"],
      ["TIGHT", "Firmly fixed"],
      ["TITLE", "Formal name"],
      ["TODAY", "This day"],
      ["TOKEN", "Symbol or piece"],
      ["TONIC", "Refreshing drink"],
      ["TOOLS", "Implement set"],
      ["TOOTH", "Single biting unit"],
      ["TOPIC", "Subject matter"],
      ["TOTAL", "Entire amount"],
      ["TOUCH", "Physical contact"],
      ["TOUGH", "Durable strength"],
      ["TOWER", "Tall structure"],
      ["TRACE", "Follow outline"],
      ["TRACK", "Path or trail"],
      ["TRADE", "Exchange goods"],
      ["TRAIN", "Transport vehicle"],
      ["TRAIL", "Path through area"],
      ["TRAMP", "Walk heavily"],
      ["TRAPS", "Capturing devices"],
      ["TREAT", "Provide care"],
      ["TREES", "Tall woody plants"],
      ["TREND", "General direction"],
      ["TRICK", "Clever deception"],
      ["TRUCK", "Cargo vehicle"],
      ["TRUST", "Confidence in"],
      ["TRUTH", "Fact or reality"],
      ["TWICE", "Two times"],
      ["UNDER", "Beneath something"],
      ["UNION", "Joined group"],
      ["UNITE", "Bring together"],
      ["UNTIL", "Up to point"],
      ["UPPER", "Higher position"],
      ["URBAN", "City-related"],
      ["USUAL", "Common pattern"],
      ["VALID", "Legally acceptable"],
      ["VALUE", "Worth or importance"],
      ["VENOM", "Poisonous fluid"],
      ["VERSE", "Line of poetry"],
      ["VIDEO", "Recorded visuals"],
      ["VIVID", "Bright and clear"],
      ["VOICE", "Human sound"],
      ["VOWEL", "Speech sound"],
      ["WAGON", "Four-wheeled cart"],
      ["WASTE", "Unneeded material"],
      ["WATCH", "Timepiece"],
      ["WATER", "Essential liquid"],
      ["WEIGH", "Measure weight"],
      ["WHERE", "In what place"],
      ["WHILE", "Period of time"],
      ["WHOLE", "Entire unit"],
      ["WIDER", "More broad"],
      ["WINDY", "Full of wind"],
      ["WOMAN", "Adult female"],
      ["WORLD", "Entire planet"],
      ["WORTH", "Value or merit"],
      ["WRITE", "Compose text"],
      ["WRONG", "Incorrect state"],
      ["YARDS", "Outdoor areas"],
      ["YEAST", "Rising agent"],
      ["YIELD", "Produce result"],
      ["YOUTH", "Young age"],
      ["ZEBRA", "Striped animal"],
      ["ZESTY", "Full of flavor"]
    ]
  };

  